name: Deploy to Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Deploy to Lightsail
        env:
          PRIVATE_KEY: ${{ secrets.LIGHTSAIL_SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.LIGHTSAIL_HOST }}
          USERNAME: bitnami
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          mkdir -p ~/.ssh
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
          
          # 배포 명령어
          scp -i private_key -r dist package.json pnpm-lock.yaml ecosystem.config.js $USERNAME@$HOST:/home/bitnami/spooky-town/
          ssh -i private_key $USERNAME@$HOST '
            cd /home/bitnami/spooky-town
            pnpm install --prod
            pm2 delete spooky-town || true
            pm2 start ecosystem.config.js
          ' 